<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

//
// !!!! DO NOT EDIT THIS FILE !!!!
// If you would like to customize your cms install use the config editor in admin 
//


// ------------------------------------------------------------------------
// 

	$config['assets']['add_app_path']				= TRUE;												// true || false
	// TODO: This should use base_path instead of sitepath so both sites can be on the same domain
	$config['assets']['cache_directory']			= 'cache/';
	$config['assets']['compression_enabled']		= TRUE;													// true || false
	$config['assets']['compression_minify']			= FALSE;													// true || false

	$config['asset_sets']['js_proto']				= array('js/jquery.min.js', 'js/cle_editor/jquery.cleditor.min.js', 'js/cle_editor/jquery.cleditor.pasteword.js', 'js/cle_editor/jquery.cleditor.xhtml.min.js', 'js/cle_editor/jquery.cleditor_init.js', 'js/prototype_min.js', 'js/prototype_element_tohtml.js', 'js/prototype_form_observer.js', 'js/scriptaculous/scriptaculous.js', 'js/scriptaculous/effects.js', 'js/scriptaculous/controls.js', 'js/scriptaculous/builder.js', 'js/scriptaculous/dragdrop.js');
	$config['asset_sets']['js_misc']				= array('js/functions.js', 'js/control.tabs.js');
	$config['asset_sets']['js_cms']					= array('js/TreeNav.js', 'js/tndr_form.js', 'js/tndr_modal.js', 'js/calendar.js');
	$config['asset_sets']['css_screen']				= array('css/reset.css', 'css/tndr_form.css', 'css/tndr_modal.css', 'css/admin.css', 'css/pickers.css', 'css/nav.css', 'css/calendar.css', 'js/cle_editor/jquery.cleditor.css');

	$config['layouts'] 								= array(
		
													'default'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/default'
														, 'assets'	=> array('js_proto', 'js_misc', 'js_cms', 'css_screen')
														)
													, 'plain'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/plain'
														, 'assets'	=> array('js_proto', 'js_misc', 'js_cms', 'css_screen')
														)
													, 'ajax'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/blank'
														, 'assets'	=> array()
														)
													, 'blank'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/blank'
														, 'assets'	=> array()
														)
													, 'xml'		=> array(
														'format'	=> 'xml'
														, 'wrapper'	=> 'wrappers/blank'
														, 'assets'	=> array()
														)
													);
		
	$config['meta_keywords']						= '';
	$config['meta_description']						= '';

	$config['auto_ajax_wrapper']					= TRUE;

											