<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

//
// !!!! DO NOT EDIT THIS FILE !!!!
// If you would like to customize your cms install use the config editor in admin 
//


// ------------------------------------------------------------------------
// 

	$config['assets']['add_app_path']				= TRUE;												// true || false
	// TODO: This should use base_path instead of sitepath so both sites can be on the same domain
	$config['assets']['cache_directory']			= 'cache/';
	$config['assets']['compression_enabled']		= TRUE;													// true || false
	$config['assets']['compression_minify']			= TRUE;													// true || false

	// $config['asset_sets']['css_all']				= array();
	// $config['asset_sets']['css_pdf']				= array();
	// $config['asset_sets']['css_print']				= array();
	// $config['asset_sets']['cssiphone']				= array();
	// $config['asset_sets']['js_top']					= array();
	// $config['asset_sets']['js_bottom']				= array();

	$config['layouts'] 								= array(
		
													'default'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/default'
														, 'assets'	=> array('js_top', 'js_bottom', 'css_all', 'css_print', 'cssiphone')
														)
													, 'plain'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/default'
														, 'assets'	=> array()
														)
													, 'ajax'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/ajax'
														, 'assets'	=> array()
														)
													, 'pdf'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/pdf'
														, 'assets'	=> array('css_pdf')
														)
													, 'popup'		=> array(
														'format'	=> 'html'
														, 'wrapper'	=> 'wrappers/default'
														, 'assets'	=> array('js_top', 'js_bottom', 'css_all', 'css_print', 'cssiphone')
														)
													, 'xml'		=> array(
														'format'	=> 'xml'
														, 'wrapper'	=> 'wrappers/default_xml'
														, 'assets'	=> array()
														)
													);
		
	$config['meta_keywords']						= '';
	$config['meta_description']						= '';

	$config['auto_ajax_wrapper']					= FALSE;

											